[package]
name = "coin-cosmos"
version = "0.1.0"
authors = ["joe <xielamenla@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../../common"}
mq = {path = "../../mq"}
bitcoin_hashes = "0.7.3"
hex = "0.3.2"
bitcoin = "0.21.0"
bytes = "0.4.8"
secp256k1 = "0.17.1"
ring = "0.16.9"
#bech32 = "0.7.1"
bech32 = { git = "https://github.com/sipa/bech32" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.101"
serde_json = "1.0"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
base64 = "0.11.0"