[package]
name = "common"
version = "0.1.0"
authors = ["wyoyw <wyoyw@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
hyper = "0.12.9"
rustc-serialize = "0.3.18"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.101"
serde_json = "1.0"
hex = "0.3"
