[package]
name = "device"
version = "0.1.0"
authors = ["wyoyw <wyoyw@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
reqwest = "0.9.22"
hyper = "0.12.9"
hyper-tls = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.101"
serde_json = "1.0"
futures = "0.1"
tokio-core = "0.1"
http = "0.1.20"
mq = {path = "../mq"}