[package]
name = "device"
version = "0.1.0"
authors = ["wyoyw <wyoyw@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
reqwest = "0.9.22"
hyper = "0.12.9"
hyper-tls = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.101"
serde_json = "1.0"
futures = "0.1"
tokio-core = "0.1"
http = "0.1.20"
mq = {path = "../mq"}
ring = "0.16.9"
base64 = "0.11.0"
aes-ctr = "0.3.0"
aes-soft = "0.3.3"
block-cipher-trait = "0.6.2"
byteorder = "1.3.2"
block-modes = "0.3.3"
hex-literal = "0.2.1"
hex = "0.3"
secp256k1 = {version ="0.17.2", features = ["rand"] }
rand = "0.6"
sha1 = "0.6.0"
rsa = "0.1.4"
lazy_static = "1.4.0"
regex = "1"
failure = "0.1.6"
log = {version = "0.4", features = ["std"]}

[target.'cfg(target_os = "macos")'.dependencies]
hidapi = "1.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
hidapi = "1.1.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.8"
